package ui;

import java.io.IOException;
import java.util.*;
import javax.swing.*;

public class ActionPanel extends javax.swing.JPanel {
    GUITimer timer = new GUITimer();
    
    /**
     * Creates new form ActionPanel
     */
    public ActionPanel() {
        initComponents();
        addMouseListener(timer);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        balanceButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        jLabel1.setText("Choose action");

        balanceButton.setText("Balance");
        balanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceButtonActionPerformed(evt);
            }
        });

        withdrawButton.setText("Withdraw");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(balanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(balanceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(withdrawButton)
                .addGap(56, 56, 56)
                .addComponent(exitButton)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        CustomerFrame.showPanel(CustomerFrame.WELCOME_PANEL);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void balanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceButtonActionPerformed
        Map<String, String> map = getAccountAndBalances();
        Set keySet = map.keySet();
        ArrayList<String> list = new ArrayList<>(1);
        keySet.forEach((item) -> list.add( String.format("%-10s%6s", item, map.get(item) ) ) );
        showItems(list.toArray(new String[list.size()]));
    }//GEN-LAST:event_balanceButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        String [] accounts = getAccounts();
        String selection = (String) JOptionPane.showInputDialog(null,"Select account", "Prompt", JOptionPane.QUESTION_MESSAGE, null, accounts, accounts[0]);
        if(selection != null){
            CustomerFrame.showPanel(CustomerFrame.WITHDRAW_PANEL);
            CustomerFrame.getWithdrawPanel().setAccountNumber( selection);
        }
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private String[] getAccounts(){
        String[] info = {};
        try {
            info = ClientConnector.getAccounts(CustomerFrame.getCustomerId());
        } catch (IOException ex) {
            info[0] = "Error";
            ex.printStackTrace();
        }
        return info;
    }
    
    private Map<String, String> getAccountAndBalances() {
        Map<String, String> info = new HashMap<>();
        try {
            info = ClientConnector.getAccountBalances(CustomerFrame.getCustomerId());
        } catch (IOException ex) {
            info.put("Error", ex.getMessage());
            ex.printStackTrace();
            //Logger.getLogger(ActionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return info;
    }
    
    private void showItems(String [] items) {
        JOptionPane.showMessageDialog(this.getParent(), items);
    }
    
    public static void main(String [] args) {
        System.out.println("ActionPanel form");
        String accounts[] = {"Strin1", "String2","String3"};
        JList list = new JList(accounts);
        JOptionPane.showInputDialog(null,"Select account", "Prompt", JOptionPane.QUESTION_MESSAGE, null, accounts, accounts[0]);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balanceButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
}
