/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;

/**
 *
 * @author DEGUZMAN
 */
public final class CustomerFrame extends javax.swing.JFrame {
    private static String customerId;
    private static final CardLayout card = new CardLayout();
    
    private static final WelcomePanel welcomePanel = new WelcomePanel();
    private static final ScanningPanel scanningPanel = new ScanningPanel();
    private static final ActionPanel actionPanel = new ActionPanel();
    private static final WithdrawPanel withdrawPanel = new WithdrawPanel();
    
    TimeThread timeThread = new TimeThread(()-> {showPanel(WELCOME_PANEL);} );
    Thread thread = new Thread(timeThread);
    GUITimer timer = new GUITimer();
    
    public static final String WELCOME_PANEL = "welcome_panel";
    public static final String SCANNING_PANEL = "scanning_panel";
    public static final String ACTION_PANEL = "action_panel";
    public static final String WITHDRAW_PANEL = "withdraw_panel";
    
    public CustomerFrame() {
        initComponents();
        
        card.addLayoutComponent(welcomePanel, WELCOME_PANEL);
        card.addLayoutComponent(scanningPanel, SCANNING_PANEL);
        card.addLayoutComponent(actionPanel, ACTION_PANEL);
        card.addLayoutComponent(withdrawPanel, WITHDRAW_PANEL);
        
        mainPanel.setLayout(card);
        mainPanel.add(welcomePanel);
        mainPanel.add(scanningPanel);
        mainPanel.add(actionPanel);
        mainPanel.add(withdrawPanel);
        
        //thread.start();
        addMouseListener(timer);
        timer.start();
    }

    public  static String getCustomerId() {
        return customerId;
    }

    public static void setCustomerId(String Id) {
        customerId = Id;
    }

    public static void showPanel(String panelName) {
        if (panelName.equalsIgnoreCase(SCANNING_PANEL)) scanningPanel.reset();
        else if (panelName.equalsIgnoreCase(WELCOME_PANEL)) setCustomerId("");
        else if (panelName.equalsIgnoreCase(WITHDRAW_PANEL)) withdrawPanel.reset();
        card.show(mainPanel, panelName);
    }

    public static WelcomePanel getWelcomePanel() {
        return welcomePanel;
    }

    public static ScanningPanel getScanningPanel() {
        return scanningPanel;
    }

    public static ActionPanel getActionPanel() {
        return actionPanel;
    }

    public static WithdrawPanel getWithdrawPanel() {
        return withdrawPanel;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(400, 306));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CustomerFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static java.awt.Panel mainPanel;
    // End of variables declaration//GEN-END:variables
}
