/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.*;

public class ScanningPanel extends javax.swing.JPanel {

    GUITimer timer = new GUITimer();

    /**
     * Creates new form scanningPanel
     */
    public ScanningPanel() {
        initComponents();
        addMouseListener(timer);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        printLabel = new javax.swing.JLabel();

        jLabel1.setText("Scan fingerprint");

        printLabel.setBackground(new java.awt.Color(255, 255, 255));
        printLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        printLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void printLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printLabelMouseClicked
        //Should allow scanning of fingerprint
        String s = getPath();
        setIcon(new ImageIcon(s));
        
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            String id = getIdForPrint(ImageIO.read(new File(s)));
            setCursor(null);
            if (id.equals("")) {
                JOptionPane.showMessageDialog(this.getParent(), "Print not found");
                return;
            } else if (id.startsWith("ERROR")) {
                CustomerFrame.showPanel(CustomerFrame.WELCOME_PANEL);
                System.err.println(id);
                return;
            }
            CustomerFrame.setCustomerId(id);

            for (int trials = 0; trials < 3; trials++) {
                String password = getPassword();
                setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                String result = verifyCustomer(id, password);
                setCursor(null);
                if (!processResult(result)) {
                    break;
                }
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this.getParent(), ex.getMessage());
            ex.printStackTrace();
            //CustomerFrame.showPanel(CustomerFrame.WELCOME_PANEL);

            //Logger.getLogger(ScanningPanel.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_printLabelMouseClicked

    private String getPassword() {
        return showPasswordInputDialog("Enter password");
    }

    private String showPasswordInputDialog(String message) {
        JPasswordField passwordField = new JPasswordField();
        JOptionPane pane = new JOptionPane();
        pane.setMessage(passwordField);

        JDialog dialog = pane.createDialog(this.getParent(), message);
        dialog.setModal(true);
        dialog.setVisible(true);
        dialog.dispose();

        String password = String.valueOf(passwordField.getPassword());
        return password;
    }

    private boolean processResult(String result) {
        if (result.equalsIgnoreCase("EXIST")) {
            CustomerFrame.showPanel(CustomerFrame.ACTION_PANEL);
            return true;
        } else if (result.equalsIgnoreCase("NOT FOUND")) {
            //showPasswordInputDialog("Credentials incorrect");
            return false;
        } else {
            System.err.println(result);
            CustomerFrame.showPanel(CustomerFrame.WELCOME_PANEL);
            return true;
        }
    }

    private String verifyCustomer(String id, String password) {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        String result;
        try {
            result = ClientConnector.verifycustomer(id, password);
        } catch (IOException ex) {
            CustomerFrame.showPanel(CustomerFrame.WELCOME_PANEL);
            result = "ERROR:";
            ex.printStackTrace();
            //Logger.getLogger(ScanningPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        setCursor(null);
        return result;
    }

    private String getPath() {
        JFileChooser fileChooser = new PictureChooser();

        int result = fileChooser.showOpenDialog(null);

        //if user clicked Cancel button on dialog, return
        if (result == JFileChooser.CANCEL_OPTION) {
            return null;
        }

        File fileName = fileChooser.getSelectedFile(); //get file

        //display error if invalid
        if ((fileName == null) || (fileName.getName().equals(""))) {
            JOptionPane.showMessageDialog(this, "Invalid Name", "error", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        return fileName.getPath();
    }

    private void setIcon(ImageIcon img) {
        SwingUtilities.invokeLater(() -> {
            Image image = img.getImage();
            image = image.getScaledInstance(printLabel.getWidth(), printLabel.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(image);
            printLabel.setIcon(icon);
        });

    }

    private String getIdForPrint(BufferedImage image) throws IOException {
        return ClientConnector.verifyPrint(image);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel printLabel;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] s) {
        JFrame frame = new JFrame("Scanning panel");
        frame.add(new ScanningPanel());
        frame.pack();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }
} //208
