/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Cursor;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class AddAccountPanel extends java.awt.Panel {
    private String idNumber ;

    public String getIdNumber() {
        return idNumber;
    }

    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }
    
    /**
     * Creates new form PasswordPanel
     *
     */
    public AddAccountPanel() {
        initComponents();
        passwordField.getDocument().addDocumentListener(new PasswordListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        generateAccountButton = new javax.swing.JButton();
        accountLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Enter password");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        generateAccountButton.setText("Generate Account Number");
        generateAccountButton.setEnabled(false);
        generateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateAccountButtonActionPerformed(evt);
            }
        });

        accountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountLabel.setText("  ");

        okButton.setText("Ok");
        okButton.setEnabled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.setEnabled(false);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        infoLabel.setForeground(new java.awt.Color(255, 0, 0));
        infoLabel.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okButton))
                    .addComponent(generateAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(accountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(generateAccountButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(exitButton))
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        AdminFrame.getAddPanel().showPanel(AddPanelController.SCANNING_PANEL);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String password = String.valueOf(passwordField.getPassword());
        new Thread(() -> verifyCustomer(getIdNumber(), password) ).start();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void generateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateAccountButtonActionPerformed
        new Thread(this::getAndSetAccount).start();
    }//GEN-LAST:event_generateAccountButtonActionPerformed

    private void setOk() {
        okButton.setEnabled(!accountLabel.getText().equals(""));
    }

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (confirmDetails()) {
            new Thread(() -> addAccount(getIdNumber(), accountLabel.getText())).start();
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        String password = String.valueOf(passwordField.getPassword());
        new Thread(() -> verifyCustomer(getIdNumber(), password) ).start();
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void addAccount(String id, String account_number) {
        try {
            String result = Connector.addAccount(id, account_number);
            if (result.equalsIgnoreCase(Constants.ACTION_SUCCESSFUL)) {
                JOptionPane.showMessageDialog(this.getParent(), "Account added successfuly");
                //AdminFrame.getAddPanel().showPanel(AddPanelController.SCANNING_PANEL);
            } else if (result.equalsIgnoreCase(Constants.ACTION_UNSUCCESSFUL)) {
                JOptionPane.showMessageDialog(this, result);
            } else {
                JOptionPane.showMessageDialog(this, result, "Info", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Info", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean confirmDetails() {
        String message = String.format("%-10s: %s%n%-10s : %s", "ID", getIdNumber(), "Account", accountLabel.getText());
        int choice = JOptionPane.showConfirmDialog(this, message, "Confirm", JOptionPane.OK_CANCEL_OPTION);
        return (choice == JOptionPane.OK_OPTION);
    }

    public void getAndSetAccount() {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        generateAccountButton.setEnabled(false);
        try {
            String account = Connector.generateAccountNumber();
            SwingUtilities.invokeLater(() -> {
                accountLabel.setText(account);
                setOk();
            });
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Info", JOptionPane.ERROR_MESSAGE);
        }
        setCursor(null);
        generateAccountButton.setEnabled(true);
    }

    private void verifyCustomer(String id, String password) {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        System.out.println("ID " + id + " password " + password);
        submitButton.setEnabled(false);
        try {
            String result = Connector.verifyCustomer(id, password);
            if (result.equalsIgnoreCase(Constants.EXIST)) {
                generateAccountButton.setEnabled(true);
                infoLabel.setText(" ");
            } else if (result.equalsIgnoreCase(Constants.DONT_EXIST)) {
                infoLabel.setText("Incorrect password");
            } else {
                JOptionPane.showMessageDialog(this.getParent(), result);
            }

        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this.getParent(), ex.getMessage(), "Info", JOptionPane.ERROR_MESSAGE);
        } finally {
            setCursor(null);
            submitButton.setEnabled(true);
        }
    }
    
    /**
     * Clear the fields
     */
    public void reset() {
        accountLabel.setText(" ");
        infoLabel.setText(" ");
        passwordField.setText(null);
    }
    
    public static void main(String [] args) throws IOException{
        JFrame frame = new JFrame("Add account panel");
        AddAccountPanel panel = new AddAccountPanel();
        panel.setIdNumber("1");
        frame.add(panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    class PasswordListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            submitButton.setEnabled(passwordField.getPassword().length > 0);
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            submitButton.setEnabled(passwordField.getPassword().length > 0);
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            submitButton.setEnabled(passwordField.getPassword().length > 0);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton generateAccountButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}//114
